import debug from "@localnerve/debug"
const str = "hello debug!"

debug("namespace:01")(str)
debug("namespace:02")(str)
debug("namespace:03")(str)
debug("namespace:04")(str)
debug("namespace:05")(str)
debug("namespace:06")(str)
debug("namespace:07")(str)
debug("namespace:08")(str)
debug("namespace:09")(str)
debug("namespace:10")(str)
debug("namespace:11")(str)
debug("namespace:12")(str)
debug("namespace:13")(str)
debug("namespace:14")(str)
debug("otherspace")(str)
debug("otherspace")(str)
debug("otherspace")(str)
debug("otherspace")(str)
debug("otherspace")(str)
console.log("")
console.log("")
console.log("")
