name: ci
on:
  push:
    branches: [ main, public-package ]
  pull_request:
    branches: [ main, public-package ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      
      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: size
        run: npm run size
