name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, public-package ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@latest
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@latest
        with:
          fetch-depth: 0

      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: size
        run: npm run size
